# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-11 13:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0009_slugfield_noop'),
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_bid1', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='User bid 1')),
                ('user_bid2', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='User bid 2')),
                ('user_bid3', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='User bid 3')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('homepage', models.URLField(blank=True, verbose_name='URL')),
                ('status', models.SmallIntegerField(choices=[(0, 'Requires moderation'), (1, 'Approved'), (2, 'Rejected')], default=1, verbose_name='Status')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bids', to='catalogue.Product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Product bid',
                'verbose_name_plural': 'Product bids',
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
        migrations.AlterUniqueTogether(
            name='productbid',
            unique_together=set([('product', 'user')]),
        ),
    ]
