# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-12 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_auto_20170211_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbid',
            name='user_bid2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='User bid 2'),
        ),
        migrations.AlterField(
            model_name='productbid',
            name='user_bid3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='User bid 3'),
        ),
    ]
