# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-24 05:57
from __future__ import unicode_literals

from django.db import migrations
import oscar.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_auto_20170223_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='proxy_class',
            field=oscar.models.fields.NullCharField(default=None, max_length=255, unique=True, verbose_name='Custom class'),
        ),
    ]
