# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-22 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20160323_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankcard',
            name='bid1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Bid 1'),
        ),
    ]
