# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-22 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_bankcard_bid1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankcard',
            name='bid1',
        ),
    ]
