# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0007_slugfield_noop'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='redeem_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='line',
            name='redeemed',
            field=models.BooleanField(default=True),
        ),
    ]
