# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0008_auto_20170301_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='redeemed',
            field=models.BooleanField(default=False),
        ),
    ]
