# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 01:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0009_auto_20170301_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='redeem_code',
        ),
        migrations.RemoveField(
            model_name='line',
            name='redeemed',
        ),
    ]
