# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-22 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_auto_20161227_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrecord',
            name='bid4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Bid 4'),
        ),
    ]
