# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-30 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0007_auto_20170329_1104'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockrecord',
            unique_together=set([('partner', 'partner_sku')]),
        ),
    ]
