# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-31 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0008_auto_20170330_1827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockrecord',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='stockrecord',
            unique_together=set([]),
        ),
    ]
